"""T78 — export: CSV, JSON, XLSX, PDF, PDF/A, as an audited action.

Scope is one entity node's evidence package — the same aggregation T62's
360 view already builds (records, linked entities, linked facts), which
is the natural "here is everything about this property/person" unit the
product's other evidence-facing features (360 view, and eventually T65's
certificate) already use.

Reuses D-8's mode policy (T67): mode="general_export" includes escrowed/
unconfirmed edges and facts but always labels them
confirmation_status="unconfirmed_machine_suggested"; mode="certificate"
excludes them entirely. This is deliberately the same boundary T67
already enforces for entity edges — an export is exactly the kind of
consumer T67 exists to gate.

Every export is audited (T07/T08): actor, scope, format, mode, and a
sha256 of the generated bytes — the hash, not the full payload, so the
audit trail can later prove exactly what left the system without storing
every export's full content in audit_dg_logs.
"""
import csv
import hashlib
import io
import json
from datetime import datetime
from typing import Any, Dict, Literal, Tuple
from uuid import UUID

from fastapi import HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.services.audit_service import log_action
from app.services.entity_360_service import get_entity_360_view

ExportFormat = Literal["json", "csv", "xlsx", "pdf", "pdf_a"]
ExportMode = Literal["general_export", "certificate"]

CONTENT_TYPES = {
    "json": "application/json",
    "csv": "text/csv",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pdf": "application/pdf",
    "pdf_a": "application/pdf",
}


def _confirmation_status(status: str) -> str:
    return "human_verified" if status == "verified" else "unconfirmed_machine_suggested"


async def gather_evidence_package(db: AsyncSession, tenant_id: UUID, node_id: UUID, mode: ExportMode) -> Dict[str, Any]:
    view = await get_entity_360_view(db, tenant_id, node_id)

    linked_entities = []
    for e in view["linked_entities"]:
        is_verified = e["status"] == "verified"
        if not is_verified and mode == "certificate":
            continue
        linked_entities.append({**e, "confirmation_status": _confirmation_status(e["status"])})

    linked_facts = []
    for e in view["linked_facts"]:
        is_verified = e["status"] == "verified"
        if not is_verified and mode == "certificate":
            continue
        linked_facts.append({**e, "confirmation_status": _confirmation_status(e["status"])})

    return {
        "node": view["node"],
        "records": view["records"],
        "linked_entities": linked_entities,
        "linked_facts": linked_facts,
        "mode": mode,
        "generated_at": datetime.utcnow().isoformat(),
    }


def _to_json_bytes(data: Dict[str, Any]) -> bytes:
    return json.dumps(data, indent=2, default=str).encode("utf-8")


def _to_csv_bytes(data: Dict[str, Any]) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)

    writer.writerow(["# ENTITY"])
    writer.writerow(["id", "entity_type", "label"])
    writer.writerow([data["node"]["id"], data["node"]["entity_type"], data["node"]["label"]])
    writer.writerow([])

    writer.writerow(["# RECORDS"])
    writer.writerow(["record_id", "record_type", "legal_status", "current_fields"])
    for r in data["records"]:
        writer.writerow([r["record_id"], r["record_type"], r["current"]["legal_status"], json.dumps(r["current"]["fields"], default=str)])
    writer.writerow([])

    writer.writerow(["# LINKED_ENTITIES"])
    writer.writerow(["edge_id", "edge_type", "tier", "direction", "confidence", "confirmation_status", "other_node_label"])
    for e in data["linked_entities"]:
        writer.writerow([e["edge_id"], e["edge_type"], e["tier"], e["direction"], e["confidence"], e["confirmation_status"], e.get("other_node", {}).get("label")])
    writer.writerow([])

    writer.writerow(["# LINKED_FACTS"])
    writer.writerow(["edge_id", "edge_type", "tier", "confidence", "confirmation_status", "field_name", "value", "document_title"])
    for e in data["linked_facts"]:
        fact = e["fact"]
        writer.writerow([e["edge_id"], e["edge_type"], e["tier"], e["confidence"], e["confirmation_status"], fact["field_name"], json.dumps(fact["value"], default=str), fact.get("document_title")])

    return buf.getvalue().encode("utf-8")


def _to_xlsx_bytes(data: Dict[str, Any]) -> bytes:
    from openpyxl import Workbook

    wb = Workbook()

    ws_records = wb.active
    ws_records.title = "Records"
    ws_records.append(["record_id", "record_type", "legal_status", "current_fields"])
    for r in data["records"]:
        ws_records.append([r["record_id"], r["record_type"], r["current"]["legal_status"], json.dumps(r["current"]["fields"], default=str)])

    ws_entities = wb.create_sheet("Linked Entities")
    ws_entities.append(["edge_id", "edge_type", "tier", "direction", "confidence", "confirmation_status", "other_node_label"])
    for e in data["linked_entities"]:
        ws_entities.append([e["edge_id"], e["edge_type"], e["tier"], e["direction"], e["confidence"], e["confirmation_status"], e.get("other_node", {}).get("label")])

    ws_facts = wb.create_sheet("Linked Facts")
    ws_facts.append(["edge_id", "edge_type", "tier", "confidence", "confirmation_status", "field_name", "value", "document_title"])
    for e in data["linked_facts"]:
        fact = e["fact"]
        ws_facts.append([e["edge_id"], e["edge_type"], e["tier"], e["confidence"], e["confirmation_status"], fact["field_name"], json.dumps(fact["value"], default=str), fact.get("document_title")])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _to_pdf_bytes(data: Dict[str, Any], pdf_a: bool = False) -> bytes:
    """Renders with reportlab. `pdf_a` embeds fonts and sets XMP/output-intent
    metadata reportlab supports out of the box — a reasonable PDF/A-flavored
    document, not a claim of full PDF/A-2b conformance validation (that
    needs a dedicated verifier, e.g. veraPDF, which isn't wired in here)."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"Evidence Export — {data['node']['label']}", styles["Title"]))
    story.append(Paragraph(f"Entity type: {data['node']['entity_type']} &middot; Mode: {data['mode']} &middot; Generated: {data['generated_at']}", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Records", styles["Heading2"]))
    if data["records"]:
        rows = [["Record type", "Legal status", "Fields"]]
        for r in data["records"]:
            rows.append([r["record_type"], r["current"]["legal_status"] or "—", str(r["current"]["fields"])[:200]])
        t = Table(rows, colWidths=[3.5 * cm, 3 * cm, 9 * cm])
        t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke)]))
        story.append(t)
    else:
        story.append(Paragraph("None.", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Linked entities", styles["Heading2"]))
    if data["linked_entities"]:
        rows = [["Type", "Tier", "Status", "Confidence", "Other entity"]]
        for e in data["linked_entities"]:
            rows.append([e["edge_type"], str(e["tier"]), e["confirmation_status"], f"{e['confidence']:.2f}" if e["confidence"] is not None else "—", e.get("other_node", {}).get("label", "—")])
        t = Table(rows, colWidths=[3 * cm, 1.5 * cm, 4 * cm, 2.5 * cm, 4.5 * cm])
        t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke)]))
        story.append(t)
    else:
        story.append(Paragraph("None.", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Linked facts", styles["Heading2"]))
    if data["linked_facts"]:
        rows = [["Field", "Value", "Status", "Confidence", "Source document"]]
        for e in data["linked_facts"]:
            fact = e["fact"]
            rows.append([fact["field_name"], str(fact["value"])[:60], e["confirmation_status"], f"{e['confidence']:.2f}" if e["confidence"] is not None else "—", fact.get("document_title") or "—"])
        t = Table(rows, colWidths=[3 * cm, 4 * cm, 4 * cm, 2 * cm, 3 * cm])
        t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke)]))
        story.append(t)
    else:
        story.append(Paragraph("None.", styles["Normal"]))

    doc.build(story)
    return buf.getvalue()


async def generate_export(
    db: AsyncSession,
    tenant_id: UUID,
    actor_id: UUID,
    node_id: UUID,
    export_format: ExportFormat,
    mode: ExportMode = "general_export",
) -> Tuple[bytes, str, str]:
    """Returns (file_bytes, filename, content_type). Always audited —
    raises before generating anything if actor_id is missing (T08)."""
    if actor_id is None:
        raise ValueError("export requires an actor")
    if export_format not in CONTENT_TYPES:
        raise HTTPException(status_code=400, detail=f"Unknown export format '{export_format}'")

    data = await gather_evidence_package(db, tenant_id, node_id, mode)

    if export_format == "json":
        content = _to_json_bytes(data)
    elif export_format == "csv":
        content = _to_csv_bytes(data)
    elif export_format == "xlsx":
        content = _to_xlsx_bytes(data)
    elif export_format == "pdf":
        content = _to_pdf_bytes(data, pdf_a=False)
    elif export_format == "pdf_a":
        content = _to_pdf_bytes(data, pdf_a=True)

    content_hash = hashlib.sha256(content).hexdigest()
    filename = f"evidence_export_{node_id}.{export_format.replace('_', '')}" if export_format != "pdf_a" else f"evidence_export_{node_id}_pdfa.pdf"

    await log_action(
        db, actor_id, tenant_id, "evidence.export",
        resource_type="entity_node", resource_id=node_id,
        details={
            "format": export_format,
            "mode": mode,
            "content_sha256": content_hash,
            "content_bytes": len(content),
            "record_count": len(data["records"]),
            "linked_entity_count": len(data["linked_entities"]),
            "linked_fact_count": len(data["linked_facts"]),
        },
    )
    await db.commit()

    return content, filename, CONTENT_TYPES[export_format]
