apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veritasdocs.fullname" . }}-worker
  labels:
    {{- include "veritasdocs.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "veritasdocs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "veritasdocs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "veritasdocs.image" (dict "registry" .Values.image.registry "repository" .Values.image.backend.repository "tag" .Values.image.backend.tag) }}
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command: ["celery", "-A", "app.tasks.worker.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ include "veritasdocs.fullname" . }}-config
          env:
            {{- include "veritasdocs.appEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
