"""update_chunks_table_schema

Revision ID: 27e405dd516b
Revises: ba93a18824ba
Create Date: 2026-07-21 11:09:58.133489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e405dd516b'
down_revision: Union[str, None] = 'ba93a18824ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('version_id', sa.UUID(), nullable=False))
    op.add_column('chunks', sa.Column('chunk_index', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_chunks_version_id'), 'chunks', ['version_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'chunks', 'document_versions', ['version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_version_id'), table_name='chunks')
    op.drop_column('chunks', 'chunk_index')
    op.drop_column('chunks', 'version_id')
    # ### end Alembic commands ###
