"""add_missing_document_fields

Revision ID: ba93a18824ba
Revises: b7a5e3c4e3b0
Create Date: 2026-07-21 10:47:07.543929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba93a18824ba'
down_revision: Union[str, None] = 'b7a5e3c4e3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('file_hash', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('file_size_bytes', sa.Integer(), nullable=False))
    op.add_column('document_versions', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_document_versions_uploaded_by'), 'document_versions', ['uploaded_by'], unique=False)
    op.create_foreign_key(None, 'document_versions', 'users', ['uploaded_by'], ['id'])
    op.add_column('documents', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_foreign_key('fk_document_current_version_id', 'documents', 'document_versions', ['current_version_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint('fk_document_current_version_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_column('documents', 'current_version_id')
    op.drop_column('documents', 'created_by')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_index(op.f('ix_document_versions_uploaded_by'), table_name='document_versions')
    op.drop_column('document_versions', 'uploaded_by')
    op.drop_column('document_versions', 'original_filename')
    op.drop_column('document_versions', 'file_size_bytes')
    op.drop_column('document_versions', 'file_hash')
    # ### end Alembic commands ###
